# First contact with Python

In [3]:
2 + 2

4

In [4]:
2 - 2

0

In [5]:
2 * 3

6

In [6]:
2 / 4

0.5

In [7]:
2 ** 8

256

In [9]:
temperature = 27

In [10]:
temperature - 10

17

In [11]:
temperature_far = temperature * 1.8 + 32

In [12]:
print(temperature_far)

80.6


In [13]:
a = 10
b = 20
a = b
c = a + 15

In [14]:
print(c)

35


In [15]:
d = b - 10

In [16]:
print(d)

10


In [18]:
name_of_satellite = 'Landsat8'

In [19]:
print(name_of_satellite)

Landsat8


In [20]:
type(name_of_satellite)

str

In [21]:
type(a)

int

In [22]:
type(temperature_far)

float

In [23]:
temperature_far + a

100.6

In [25]:
name_of_satellite * 10

'Landsat8Landsat8Landsat8Landsat8Landsat8Landsat8Landsat8Landsat8Landsat8Landsat8'

In [26]:
name_of_satellite + " is a satellite"

'Landsat8 is a satellite'

In [27]:
round?

Signature: round(number, ndigits=None)
Docstring:
Round a number to a given precision in decimal digits.

The return value is an integer if ndigits is omitted or None.  Otherwise
the return value has the same type as the number.  ndigits may be negative.
Type:      builtin_function_or_method


In [32]:
interger_value = round(1.6) + 10

In [33]:
print(interger_value)

12


In [34]:
type(interger_value)

int

In [35]:
temperatures = [-1, 5, 2, 7, 10]

In [36]:
type(temperatures)

list

In [39]:
print(temperatures[4])

10


In [40]:
max(temperatures)

10

In [41]:
min(temperatures)

-1

In [42]:
len(temperatures)

5

In [44]:
# The order of operations is from the inside to the outside
print(temperatures[len(temperatures) - 1])

10


**Beware:** the order of operations is inside out. $\int_V x dx$

In [45]:
temperatures_far = temperatures * 1.8 + 32

TypeError: can't multiply sequence by non-int of type 'float'

In [46]:
import numpy

In [47]:
type(numpy)

module

In [48]:
numpy.max?

Signature:
numpy.max(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Docstring:
Return the maximum of an array or maximum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the maximum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See `ufuncs-output-type` for more details.

keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the input array.

    If the default value is pas

In [49]:
import numpy as np

In [51]:
np.max?

Signature:
np.max(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Docstring:
Return the maximum of an array or maximum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the maximum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See `ufuncs-output-type` for more details.

keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the input array.

    If the default value is passed

In [52]:
temperatures_array = np.array(temperatures)

In [53]:
type(temperatures_array)

numpy.ndarray

In [54]:
temperatures_array[0]

-1

In [55]:
temperatures_array[4]

10

In [56]:
max(temperatures_array)

10

In [58]:
temperatures_far = temperatures_array * 1.8 + 32

In [59]:
print(temperatures_far)

[30.2 41.  35.6 44.6 50. ]


In [60]:
temperatures_array.dtype

dtype('int64')

In [61]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

In [62]:
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


In [63]:
matrix_far = matrix * 1.8 + 32

In [64]:
print(matrix_far)

[[33.8 35.6]
 [37.4 39.2]
 [41.  42.8]]


In [66]:
matrix[0, 0]

1

In [67]:
matrix[0, 1]

2

In [69]:
matrix[3, 1]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [71]:
# Slicing an array
matrix[0 : 2, 0 : 2]

array([[1, 2],
       [3, 4]])

In [72]:
np.max(matrix)

6

In [ ]:
110101

In [74]:
1*1 + 0 + 2**2 + 0  + 2**4 + 2**5

53

In [75]:
data = np.array([1, 2, 3, 4, 600], dtype="int8")

In [76]:
print(data)

[ 1  2  3  4 88]


In [77]:
data.dtype

dtype('int8')

In [78]:
matrix.shape

(3, 2)